### ISSUE TITLE
Problems...

### ISSUE THREAD

**Issue by Roxy-3DPrintBoard** [MarlinFirmware/MarlinDocumentation#11]
@jbrazio 

Hey...  Sorry for the inconvenience!   I was cleaning up the teams and privileges, and I got rid of (what I thought was) an unused, duplicate team name.   And you disappeared.   But I've sent out a new invite and when you accept, I'll get things back to where they used to be.

**Comment by jbrazio** [comment]
It's OK, cleaning up the house usually brings good things.
btw @Roxy-3DPrintBoard I dunno if this is a side effect or intended, but I seem to have more privileges than before over the other repos.

**Comment by Roxy-3DPrintBoard** [comment]
Yeah...  That part of what happened was intended...

**Comment by jbrazio** [comment]
Thank you for the trust.
