### ISSUE TITLE
Issue with Unified Bed Level starter code

### ISSUE THREAD

**Issue by VibroAxe** [MarlinFirmware/MarlinDocumentation#128]
The UBL get started code makes a reference to
`G26 C P T3.0`
(https://github.com/MarlinFirmware/MarlinDocumentation/blame/master/_features/unified_bed_leveling.md#L63)

I can find no reference to the T parameter anywhere in the G26 documentation.

From looking at the git log this used to be O3.0 and control the ooze setting (which makes sense). Is the documentation wrong, or are we missing any documentation on this new mysterious T parameter ;) ?

**Comment by thinkyhead** [comment]
I'm guessing this was changed from some other letter in the past. Most likely it is now `F` (filament diameter).
