### ISSUE TITLE
M43 documentation is not up to date WRT the implementation

### ISSUE THREAD

**Issue by TheSFReader** [MarlinFirmware/MarlinDocumentation#139]
The M43 gcode doc is not up to date WRT the implementation 
- The L has only changed as a selector for one of the options, the E is still used for endstop tracking.
- The S option (to testservo probe) is missing

The different sub-options would need clean argument explanations.

**Comment by thinkyhead** [comment]
One for you, @Bob-the-Kuhn, when you have the time…

**Comment by shitcreek** [comment]
Looks like it's all up to date now.
see http://marlinfw.org/docs/gcode/M043-T.html
