### ISSUE TITLE
Cannot communicate with RAMPS 1.4 w/TMC2130 enabled

### ISSUE THREAD

**Issue by Welsh-1** [MarlinFirmware/MarlinDocumentation#151]
Using atom successfully compiled and uploaded to two Panucatt rearm boards.

Board 1 setup with TMC2130s - Unable to communicate with board when TMC2130s are enabled
Board 2 setup with A4988 Drivers - Able to communicate with RAMPS board with no issues.

Problem re-created by enabling TMC2130s on Board 2 (after swap out) and unable to communicate using Pronterface

Boards - RAMPS 1.4
Panucatt Rearm
Pronterface version 1.6.0
Windows 10 - Comms Ports (default settings)
Com 7 - setup for Board 1
Com 8 - setup for Board 2

Configuration for both in Configuration.h 
#define SERIAL_PORT 0
#define SERIAL_PORT_2 -1
#define BAUDRATE 1000000 - Multiple board rates configured and tested.

**Comment by thinkyhead** [comment]
I think you want to post this at https://github.com/MarlinFirmware/Marlin/issues
