### ISSUE TITLE
M104, M109 (and others) can take a T parameter in Marlin 1.1.8

### ISSUE THREAD

**Issue by b-morgan** [MarlinFirmware/MarlinDocumentation#161]
I looked at the Marlin sources for 1.1.8 when someone pointed out that, according to this documentation, using `T0` and `T1` with `M104` and `M109` wasn't supported. The code says they do (look for `get_target_extruder_from_command` in `Marlin_main.cpp`).

**Comment by thinkyhead** [comment]
Thanks for the note. It has now been patched!
