### ISSUE TITLE
M118 is documented on RepRapWiki but not here

### ISSUE THREAD

**Issue by b-morgan** [MarlinFirmware/MarlinDocumentation#162]
Documentation for [M118](http://reprap.org/wiki/G-code#M118:_Echo_message_on_host) is missing from here.

**Comment by Roxy-3D** [comment]
It's some what documented at the top of Marlin_main.cpp:
```
 * M117 - Display a message on the controller screen. (Requires an LCD)
 * M118 - Display a message in the host console.
 * M119 - Report endstops status
```

**Comment by b-morgan** [comment]
Then what is the page [http://marlinfw.org/meta/gcode/](url) for? Most people use that page to determine what Gcodes are supported by Marlin. Most people don't read the sources. I thought this was an issue against the documentation, not the source code. Am I wrong?

**Comment by Roxy-3D** [comment]
Yes, it should be documented better.   I was just saying there is a tiny amount of documentation 'here'.

**Comment by filipgoc** [comment]
@b-morgan This is an open source project. When you discover something, it's often an omission rather than a design flaw...

**Comment by b-morgan** [comment]
@filipgoc I understand that and if the page in question wasn't so complicated, I'd have attempted to fix it myself.

**Comment by thinkyhead** [comment]
Thanks for the heads-up @b-morgan! I've now added a page for `M118` to the G-code docs.
