### ISSUE TITLE
Enhancement Request: K-factor Calibration Pattern

### ISSUE THREAD

**Issue by b-morgan** [MarlinFirmware/MarlinDocumentation#199]
I'd like to see (at least) two simple text fields, one labeled Printer and one labeled Filament. These would just get copied into the generated G-code as comments near the top (next to the "; Created:" comment).

A third text field (labeled Filename) could be added (and used) so that multiple outputs could have meaningful names instead of all being named kfactor.gcode.

**Comment by thinkyhead** [comment]
@ikarisan

**Comment by shitcreek** [comment]
I've added the requested enhancement, now awaiting site rebuild.
#c1de272007b3c763c95f29c4ec90f80d6d6caa5b
