### ISSUE TITLE
M208 S/W parameters description error

### ISSUE THREAD

**Issue by marchyman** [MarlinFirmware/MarlinDocumentation#208]
The description for the S and W parameters is incorrect for the M208 - Set Firmware Recovery command

```
[S<length>] | Recover length
[W<length>] | Recover swap length (multi-extruder)

```

The parameters are are a plus/minus offset to the lengths set with the M207 command, not absolute lengths.  Suggested change:

```
[S<length>] | Recover length offset
[W<length>] | Recover swap length offset (multi-extruder)

```

**Comment by thinkyhead** [comment]
Patched and uploading now!
