### ISSUE TITLE
Bitmap Converter comma issue

### ISSUE THREAD

**Issue by tnn85** [MarlinFirmware/MarlinDocumentation#216]
There is a bug in the Bitmap Converter for _Bootscreen.h and _Statusscreen.h generation.

http://marlinfw.org/tools/u8glib/converter.html

The last element of the bmp array is not comma separated from the previous one.

Arduino IDE throws a compilation error if the generated bootscreen was copy&pasted to the _Bootscreen.h file in the Marlin folder.

**Comment by thinkyhead** [comment]
This will be patched in the next version, which also adds support for Marlin 2.0.
