### ISSUE TITLE
External closed loop controller use SPI

### ISSUE THREAD

**Issue by crazyp1g** [MarlinFirmware/MarlinDocumentation#220]
I want to use an external closed-loop controller such as tmc4361 on xyz axis. How do I configure Marlin ？and Is there such a branch？

**Comment by thinkyhead** [comment]
Marlin does include this support. Look at the `EXTERNAL_CLOSED_LOOP_CONTROLLER` option.

This Issue Queue is for Marlin documentation contributions and suggestions, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y
