### ISSUE TITLE
Platformio Mac install

### ISSUE THREAD

**Issue by keithellis74** [MarlinFirmware/MarlinDocumentation#226]
Can we have some instructions for installing a working instance of Platformio on Mac OS 10.14.5 please.  Tk inter is not installed with this version Mac OS.  I have tried installing tkinter via https://platform.activestate.com/keithellis/ActiveTcl-8.6/distributions?new_project=true, but it is not picked up by platformio.
I get the following error when selecting AutoBuild/PIO Build.
thank you.
<img width="481" alt="Screenshot 2019-06-17 at 21 26 45" src="https://user-images.githubusercontent.com/6196195/59638469-7baf2d80-9150-11e9-9197-195ba349bda7.png">

**Comment by thinkyhead** [comment]
Yeah, I got stuck there too. It seemed to resolve itself, but I'm not sure why. As I recall I may have enabled an option in Visual Studio Code related to the shell environment, but I can't remember which one. If I can find that info I'll let you know.

**Comment by thinkyhead** [comment]
@charlesmike hello

**Comment by shitcreek** [comment]
![givePermissionToRunTerminal](https://user-images.githubusercontent.com/45380455/60750214-e80c9800-9f6a-11e9-8471-5011604cef23.png)

Confirm working after granting permission to modify shell, doesn't come to front.

**Comment by shitcreek** [comment]
These instructions worked for me on Mac: http://marlinfw.org/docs/basics/install_platformio.html
