### ISSUE TITLE
Fix converter(2).js

### ISSUE THREAD

**Issue by Ludy87** [MarlinFirmware/MarlinDocumentation#232]
https://github.com/Ludy87/MarlinDocumentation/commit/adbccd23dcbd0e49a7d28c997ae012844c22ad6d

**Comment by thinkyhead** [comment]
Commit added, thanks!

**Comment by Ludy87** [comment]
Sorry @thinkyhead, i have a new Fix for https://github.com/MarlinFirmware/Marlin/issues/14542#issuecomment-509446674

https://github.com/Ludy87/MarlinDocumentation/commit/183f9a552b3fac952b1f094ae04b8ab6f8a98815

https://github.com/Ludy87/MarlinDocumentation/commit/34ae59f236ff4900290186d085ac4d734ba451d8

**Comment by thinkyhead** [comment]
I'll bring them over when time allows….
