### ISSUE TITLE
[Bug] Online image converter not Marlin 2.0 compatible

### ISSUE THREAD

**Issue by VanessaE** [MarlinFirmware/MarlinDocumentation#233]
~~Foreword:  I'm putting this here in the Marlin issue tracker because I don't see a more appropriate place.~~ Issue moved here at @Ludy87's suggestion.

### Description

The online image converter located at http://marlinfw.org/tools/u8glib/converter.html has several minor bugs, when generating a status screen logo.  ~~The code block generated has incorrect syntax, and~~ what it creates is not Marlin-2.0 compatible at any rate:
-  [ ] The converter sets the image width as `STATUS_SCREENWIDTH`, but Marlin 2.x expects `STATUS_LOGO_WIDTH`.
-  [ ] The name of the array (?  what we call a table in Lua) is incorrect.  The converter sets it to 
`status_screen0_bmp` but Marlin expects `status_logo_bmp`.
-  [X] Minor nitpick:  the converter is appending a redundant comma to the end of the bitmap data. (fixed by 7ac32c6ab3ed0d3d461b942e07990b88bf2ea6aa)
-  [ ] Not sure if it matters:  `#pragma once` is used in other example status screen images supplied with Marlin, but the converter does not insert that directive into its output.
-  [X] Also, the converter is inserting at least one space between items in the last line of output, where it should be inserting a comma.  `  B00000000,B00000000,B00000000,B00000001 B11000000,`   This confuses the compiler, causing it to error out (look between the 4th and 5th bytes). (fixed by 7ac32c6ab3ed0d3d461b942e07990b88bf2ea6aa)

3. On the converter page, the text "If this tool doesn't work in your browser, use the server-side tool at digole.com." links (at the end there) to a page that declares itself as deprecated, which then recommends users follow another link to an "online emulator", which, to put it politely, looks like something straight out of 1990, and seems not to be particularly useful...  I recommend just deleting this line of text from the page.

### Steps to Reproduce

Browse to http://marlinfw.org/tools/u8glib/converter.html and plug in a suitable image file, examine the output.

**Expected behavior:**

I should get a block of code I can copy/paste directly into _Statusscreen.h

**Actual behavior:**

I got a block block of code that required an enormous :wink: 4-line change to make it work.

#### Additional Information
<details><summary>_Statusscreen.h as generated by the converter (outdated)</summary>

```
/**
 * Made with Marlin Bitmap Converter
 * http://marlinfw.org/tools/u8glib/converter.html
 *
 * This bitmap from the file 'marlin-prusa-i3-status-screen-logo.png'
 */
#define STATUS_SCREENWIDTH 40
const unsigned char status_screen0_bmp[] PROGMEM = {
  B00000001,B11111111,B00000001,B00000000,B00000000,
  B00000010,B00000111,B00000011,B00000000,B00000000,
  B00000100,B01010011,B00000011,B00000000,B00000000,
  B00000100,B10101001,B00000111,B10000000,B00000000,
  B00000100,B10101001,B00000111,B10000000,B00000000,
  B00000100,B10101001,B00000111,B11001110,B00000000,
  B00000100,B10001001,B00001000,B01111010,B00000000,
  B00000010,B00000010,B00001111,B10010100,B00000000,
  B00000001,B11111100,B00011111,B11111100,B00000000,
  B00000000,B00000000,B00111111,B11111110,B00000000,
  B00000000,B00000001,B11111111,B11111111,B00000000,
  B00000011,B11111111,B11110111,B11111111,B10000000,
  B00000000,B00001111,B10111011,B11111111,B10000000,
  B00000000,B00000001,B11111011,B11101101,B11000000,
  B00000000,B00000010,B11111011,B11110101,B11000000,
  B00000000,B00000101,B10110111,B11110101,B11000000,
  B00000110,B00001110,B00001111,B11111110,B11000000,
  B00000101,B00000000,B00000000,B00000110,B11000000,
  B00000101,B01010101,B00110011,B10000110,B11000000,
  B00000110,B01100101,B01100100,B10000011,B11100000,
  B00000100,B01000101,B00110101,B10000010,B11100000,
  B00000100,B01000011,B01100010,B10000001,B11110000,
  B00000000,B00000000,B00000000,B00000001,B11010000,
  B00000000,B00001110,B00000000,B00000011,B10000000,
  B00000000,B00100010,B00000000,B00000111,B10000000,
  B00000000,B00000100,B00000001,B11111111,B10000000,
  B00000000,B00100010,B00000111,B11111100,B10000000,
  B00000000,B00100010,B00001100,B00000000,B11000000,
  B00000000,B00101100,B00000000,B00000111,B11000000,
  B00000000,B00000000,B00000000,B00000001 B11000000,
};
```
</details>

<details><summary>The corrected code (outdated, see below)</summary>

```
/**
 * Made with Marlin Bitmap Converter
 * http://marlinfw.org/tools/u8glib/converter.html
 *
 * This bitmap from the file 'marlin-prusa-i3-status-screen-logo.png'
 */

#pragma once

#define STATUS_LOGO_WIDTH 39

const unsigned char status_logo_bmp[] PROGMEM = {
  B00000001,B11111111,B00000001,B00000000,B00000000,
  B00000010,B00000111,B00000011,B00000000,B00000000,
  B00000100,B01010011,B00000011,B00000000,B00000000,
  B00000100,B10101001,B00000111,B10000000,B00000000,
  B00000100,B10101001,B00000111,B10000000,B00000000,
  B00000100,B10101001,B00000111,B11001110,B00000000,
  B00000100,B10001001,B00001000,B01111010,B00000000,
  B00000010,B00000010,B00001111,B10010100,B00000000,
  B00000001,B11111100,B00011111,B11111100,B00000000,
  B00000000,B00000000,B00111111,B11111110,B00000000,
  B00000000,B00000001,B11111111,B11111111,B00000000,
  B00000011,B11111111,B11110111,B11111111,B10000000,
  B00000000,B00001111,B10111011,B11111111,B10000000,
  B00000000,B00000001,B11111011,B11101101,B11000000,
  B00000000,B00000010,B11111011,B11110101,B11000000,
  B00000000,B00000101,B10110111,B11110101,B11000000,
  B00000110,B00001110,B00001111,B11111110,B11000000,
  B00000101,B00000000,B00000000,B00000110,B11000000,
  B00000101,B01010101,B00110011,B10000110,B11000000,
  B00000110,B01100101,B01100100,B10000011,B11100000,
  B00000100,B01000101,B00110101,B10000010,B11100000,
  B00000100,B01000011,B01100010,B10000001,B11110000,
  B00000000,B00000000,B00000000,B00000001,B11010000,
  B00000000,B00001110,B00000000,B00000011,B10000000,
  B00000000,B00100010,B00000000,B00000111,B10000000,
  B00000000,B00000100,B00000001,B11111111,B10000000,
  B00000000,B00100010,B00000111,B11111100,B10000000,
  B00000000,B00100010,B00001100,B00000000,B11000000,
  B00000000,B00101100,B00000000,B00000111,B11000000,
  B00000000,B00000000,B00000000,B00000001,B11000000
};
```
</details>

Note: I'm not sure whether it was really necessary to set the width to 39 pixels, but that's what one of the other stock Marlin images used, and I assumed a value one pixel less than a whole byte's worth may be important, so I followed suit.

Incidentally, here is the image I used:
![marlin-prusa-i3-status-screen-logo](https://user-images.githubusercontent.com/1733537/60763397-aa2e7300-a041-11e9-998d-fa9dc59648b6.png)

EDIT: See also https://github.com/MarlinFirmware/Marlin/issues/14534#issuecomment-509825504 for updated image (and code for it).

**Comment by thinkyhead** [comment]
It's on the TODO list, but so many other things TODO…

**Comment by VanessaE** [comment]
Fair enough. :smiley:

**Comment by benebrady** [comment]
The state of the bitmap converter is not even Marlin 1.1.x compatible at this point. An extra byte of Zero is added to each line in the file.  This zip file contains 2 bootscreens. Both were generated by the bitmap converter. One was edited to remove the extra byte of Zero at the end of each line. The edited file works under 8 bit controllers such as the MKS Gen L and MKS Gen 1.4, but it DOES not work for SKR 1.3 boards. The NON-edited bootscreen file also does not work in the 8 bit controllers.
[_Bootscreen.zip](https://github.com/MarlinFirmware/MarlinDocumentation/files/3375279/_Bootscreen.zip)

**Comment by thinkyhead** [comment]
The author of the tool is aware of its shortcomings.

**Comment by VanessaE** [comment]
@shitcreek why did you close this?

**Comment by shitcreek** [comment]
Sorry I didn't see the checklist and thought it was all resolved.

**Comment by LMF5000** [comment]
Can confirm bug - this does not work on SKR E3 because it's adding an extra B00000000 entry at the end of each line. If you count the number of entries, you'll see there's 17 [Bxxxxxxxx] entries per line, instead of 16. The result is a garbled image. The interim solution is to open the output file with notepad++ and delete the last entry on each line, or run a find and replace, finding "B00000000\r\n" and replacing with "\r\n". Then manually delete the very last B00000000 at the bottom of the file.

**Comment by shitcreek** [comment]
I've corrected the code to address the remaining issues and the extra column. Now awaiting site rebuild @thinkyhead
