### ISSUE TITLE
Add LCD message to K-factor Calibration Pattern

### ISSUE THREAD

**Issue by haarp** [MarlinFirmware/MarlinDocumentation#235]
The generator on http://marlinfw.org/tools/lin_advance/k-factor.html is quite useful! I have one suggestion tho, I'd like it to add M117 LCD messages that show the currently active K-factor. This would make it easier to spot the correct value while it's being printed, instead of having to count, or wait until it finishes and prints the line numbering.

Thanks!

**Comment by shitcreek** [comment]
Added, awaiting site rebuild.

**Comment by haarp** [comment]
Nice, thanks!
