### ISSUE TITLE
Wrong G-code in Bed Leveling documentation

### ISSUE THREAD

**Issue by Uinden** [MarlinFirmware/MarlinDocumentation#262]
http://marlinfw.org/docs/gcode/G029-mbl.html
Examples say:
```
(Marlin 2.x) Modify some mesh points and view the new mesh:
> S3 I2 J2 Z0.042
> S3 I1 J1 Z-0.666
> S0
3x3 mesh. Z offset: 0
Measured points:
       0      1       2
0 +0.011 -0.020  -0.026
1 +0.017 -0.666  -0.019
2 +0.022 -0.030  +0.042
```
And I tried over and over again to send S0 or S3, changing settings, re-compiling, but Marlin keep saying `Unknown command: "S0"`

So turns out its not `S0` or `S3`. 
Its `G29 S0` and `G29 S3 ...`
Please fix it.

**Comment by thinkyhead** [comment]
Fixed, thanks!
