### ISSUE TITLE
marlinfw.org is displaying a 404 page

### ISSUE THREAD

**Issue by Ghostkeeper** [MarlinFirmware/MarlinDocumentation#266]
I'm not sure if this is the correct place to notify you of this, but I can't find any other. Maybe you've already seen this, too.

The website www.marlinfw.org currently displays a 404 page, saying that the Github Pages website can't be found.

![Screenshot in Firefox](https://user-images.githubusercontent.com/2448634/71450869-61db4c80-276a-11ea-8119-8ab9db8a170b.png)

I'm seeing some recent work on the deployment logic in the history of this repository. Perhaps this has something to do with it?

**Comment by Ghostkeeper** [comment]
Oops, seems someone else was reporting this at the same time. I'm sorry. Please continue discussion here: https://github.com/MarlinFirmware/MarlinDocumentation/issues/265

**Comment by thinkyhead** [comment]
We tend to notice this, so no need to report it unless it persists for days.
