### ISSUE TITLE
No way to switch color schemes on iPad browser

### ISSUE THREAD

**Issue by ManuelMcLure** [MarlinFirmware/MarlinDocumentation#271]
The "sun/moon" icon that shows up on PC browsers or on an iPhone browser does not show up on the iPad so there is no way to switch color schemes.

**Comment by thinkyhead** [comment]
Odd! I have an iPad and it shows up for me. Which model and what browsers?

**Comment by ManuelMcLure** [comment]
This is a 2018 iPad (not iPad Pro) running Safari on the latest version of iPadOS.
However, I just noticed that although the icon isn't available in portrait mode, it does appear in landscape, so this is much lower priority.

**Comment by ManuelMcLure** [comment]
This seems to no longer be an issue.
