### ISSUE TITLE
Left side navigation panel in G-code documentation page broken

### ISSUE THREAD

**Issue by guruathwal** [MarlinFirmware/MarlinDocumentation#275]
The left side navigation panel in the G-code documentation page looks broken.

![image](https://user-images.githubusercontent.com/22422544/76409827-f2fab080-63b4-11ea-880a-11a12c1bda9a.png)

**Comment by drzejkopf** [comment]
I've noticed the same problem, and it's extremely annoying because gcode commands are not listed in Help>Gcode tab also and it's hard to navigate

**Comment by guruathwal** [comment]
it looks like it is fixed now...
