### ISSUE TITLE
Linear Advance Calibration Generates an Unnecessary Move

### ISSUE THREAD

**Issue by gayuha** [MarlinFirmware/MarlinDocumentation#276]
When I generate the calibration pattern, this line is generated near the beginning:

`G1 X100 Y100 F9000 ; move to start`

This moves the nozzle extremely fast and close to the bed, and risks scratching it.

**Comment by thinkyhead** [comment]
I've added a 5mm raise just after G28 and before heating. That should do the trick.

**Comment by gayuha** [comment]
That is indeed better, but I thought this line should simply be removed. I remove it manually before printing and it works ok. Is there a purpose for it?

**Comment by thinkyhead** [comment]
More a question for the tool's author, @Sineos.

**Comment by Sineos** [comment]
The ; move to start lines are generated whenever we need to move to a new starting point without printing. The speed is determined with the Movement Speed setting in the tool.

**Comment by gayuha** [comment]
I refer specifically to the first ` ; move to start` line that is generated. It just moves the nozzle to the center of the bed. No printing happens there.
