### ISSUE TITLE
Linear Advance Calibration "Save as Default" Does Not Always Work

### ISSUE THREAD

**Issue by gayuha** [MarlinFirmware/MarlinDocumentation#277]
The "Save as Default" button in the calibration tool does not save the values for K start, end and stepping. It seems to work for the other fields, but I didn't thoroughly check it.

**Comment by thinkyhead** [comment]
I've changed the K-factor form so that saved values will be preserved. I don't think the checks and changes applied at load will be missed. They really should just be checking for reasonable values based on the other choices, so that may be added later.
