### ISSUE TITLE
Section: Probe Offsets [out of date]

### ISSUE THREAD

**Issue by k4my4b** [MarlinFirmware/MarlinDocumentation#287]
commands mentioned under said seciton have been replaced,  so I believe.
e.g. X_PROBE_OFFSET_FROM_EXTRUDER, Y_PROBE_OFFSET_FROM_EXTRUDER etc ...

**Comment by thinkyhead** [comment]
The entire section is out of date. We're trying to automate page generation for configuration options, but it's a large project and will not be ready for a while.
