### ISSUE TITLE
Request: K Factor Pattern Increased precision

### ISSUE THREAD

**Issue by StephS** [MarlinFirmware/MarlinDocumentation#296]
I tend to use a microscope when calibrating my K-Factor. It might seem ridiculous, but I have had good results.
However, when I set the K factor stepping to high precision, like 3 digits, it only prints out 2 digits. I had to edit the files manually to increase precision.

I propose either of 2 solutions:
Increase default precision of the print (currently 2 digits).
or, detect the precision of the K factor stepping value and set precision to that amount.
Otherwise it's kind of misleading when you enter in 0.005 as the stepping, but you really just get values like 0.01, 0.01, 0.02, 0.02, ...

https://github.com/MarlinFirmware/MarlinDocumentation/blob/fad13b57fb454b5f0f2579aeac91abd2947b78c6/_tools/lin_advance/k-factor.js#L488

**Comment by thinkyhead** [comment]
Thanks for the suggestion. The change will be published shortly.
