### ISSUE TITLE
Marlin Bugfix 2.0 Crashes into X tower after delta Calibration routine

### ISSUE THREAD

**Issue by jonawald** [MarlinFirmware/MarlinDocumentation#305]
I recently rebuilt my printer with a new Board, new stepper drivers and new Firmware. Now, when I go to do Delta calibration to set up printer for first time, calibration fails by crashing into X tower.

Everything seems to go good to start off with. It does the center probe, then does probes around the edge of the bed and goes back to the middle for a probe. Its' after this step where instead of homing all the axis, it homes only the X and crashes the carriage into the X tower. Homeing works well otherwise.

https://photos.app.goo.gl/HeEGG5jUtF9h5saWA Here is a video of this behaviour.  I did make a test print, and everything else worked except for the bed not being quite where it should be for first layer. Everything else is working.

I tried posting this to the Facebook group, but there was no helpful response after over a day of waiting. 
[Marlin-bugfix-2.0.x.zip](https://github.com/MarlinFirmware/MarlinDocumentation/files/4582016/Marlin-bugfix-2.0.x.zip)

**Comment by thinkyhead** [comment]
This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose) to the main project repository.
