### ISSUE TITLE
M851 XYZ Probe Offset Gcode documentation is outdated

### ISSUE THREAD

**Issue by lnlp** [MarlinFirmware/MarlinDocumentation#311]
Documentation https://marlinfw.org/docs/gcode/M851.html says

> The default (factory) values are set by
> 
> X_PROBE_OFFSET_FROM_EXTRUDER
> Y_PROBE_OFFSET_FROM_EXTRUDER
> Z_PROBE_OFFSET_FROM_EXTRUDER

While Marlin 2.0.5.3 code SanityCheck.h says
```cpp
#elif defined(X_PROBE_OFFSET_FROM_EXTRUDER) || defined(Y_PROBE_OFFSET_FROM_EXTRUDER) || defined(Z_PROBE_OFFSET_FROM_EXTRUDER)
  #error "[XYZ]_PROBE_OFFSET_FROM_EXTRUDER is now NOZZLE_TO_PROBE_OFFSET. Please update your configuration."
```

**Comment by shitcreek** [comment]
I've added the clarification for this. Thanks.
