### ISSUE TITLE
[FR] Unretract speed in linear advance calibration pattern page

### ISSUE THREAD

**Issue by josedpedroso** [MarlinFirmware/MarlinDocumentation#317]
### Description

It would be nice to have the possibility to set a separate unretraction speed in http://marlinfw.org/tools/lin_advance/k-factor.html

Currently, the left side of the calibration patterns I print is very faded, especially as the k-factor increases. I incorrectly avoided higher k-factors because of this.

Today, I tried manually replacing 

`G1 E5 F3000 ; un-retract`

with

`G1 E5 F1500`

and the problem was solved, I had no underextrusion in the beginning of the lines, and I correctly determined that a higher k-factor was exactly what I needed.

### Feature Workflow

An input box for the unretraction speed in the page.

**Comment by shitcreek** [comment]
I've created a PR based on your requests: https://github.com/MarlinFirmware/MarlinDocumentation/pull/321
