### ISSUE TITLE
The link to "Unified bed leveling" is broken.

### ISSUE THREAD

**Issue by damien-ipika** [MarlinFirmware/MarlinDocumentation#33]
Everything is on the title.

**Comment by landodragon141** [comment]
Where is this "link" located?

**Comment by damien-ipika** [comment]
Hi,

The links are in this page : https://www.marlinfw.org/

If you click on image "Unified bed leveling " or "Rich G-Code Support " in
the bottom of the page.


Best regards.


2016-10-21 16:08 GMT+02:00 landodragon141 <notifications@github.com>:

**Comment by jbrazio** [comment]
It has been fixed.
