### ISSUE TITLE
Inconsistency in GCode doc for M400 and M5

### ISSUE THREAD

**Issue by mbenkmann** [MarlinFirmware/MarlinDocumentation#330]
The example here 

https://marlinfw.org/docs/gcode/M400.html

reads

```
M400
M5    ; Without M400 this happens too soon 
```

but the doc here

https://marlinfw.org/docs/gcode/M005.html

says

**Description**
**Wait for moves to complete**, then turn off the spindle / laser power and PWM.

One of the 2 pages must be wrong.

**Comment by thinkyhead** [comment]
Thanks! I'll change the example on M400.
