### ISSUE TITLE
Ubl documentation/instructions need more clearly

### ISSUE THREAD

**Issue by zonalimitatore** [MarlinFirmware/MarlinDocumentation#361]
Some user now use ubl.But looking at the site like "first approach" I don't think it's very helpful.
I mean that some command aren't available,and,for example,it tell do P1,2,3,4. But in other page,tell P3 isn't necessary.
Isn't specified that need a initial gcode for enable it (in 2 ways)
And so on
I'd like to be helpful,but it confuse me too
Can be improved, removing old commands,or unnecessary?

**Comment by Vertabreak** [comment]
Will have a look see if I can provide better examples for ubl use cases.

**Comment by shitcreek** [comment]
I think @Vertabreak 's PR has addressed this concern.
