### ISSUE TITLE
M118: Add info about serial port output

### ISSUE THREAD

**Issue by Teddyz** [MarlinFirmware/MarlinDocumentation#378]
Please add info about Parameter [P1] and [P2]. 
I made an example below, but I am neither native English nor an expert on this topic.

**Description**
Send a message to the connected host for display in the host console or to perform a host action. Can also send messages to the serial ports.

**Notes**
The E, A and P parameters must precede the message.

**Usage**
M118 [A1] [E1] [P1] [P2] [string]

**Parameters**
[P1] | Send the message on the main host serial port. 
[P2] | Send the message on the second host serial port. Requires `SERIAL_PORT_2`

**Comment by shitcreek** [comment]
https://github.com/MarlinFirmware/MarlinDocumentation/commit/412d14c4af10ab879c5231fdaa7e2d270f123d24
