### ISSUE TITLE
FYI, Additional content

### ISSUE THREAD

**Issue by ctkjose** [MarlinFirmware/MarlinDocumentation#391]
FYI: The wiki pages at reprap.org for RAMPS 1.4 (and related boards) was updated with much more info related to Marlin Firmware, also the page on mechanical endstops.

These pages should be able to complement related sections on Marlins's documentation.

https://reprap.org/wiki/RAMPS_1.4

https://reprap.org/wiki/Mechanical_Endstop

**Comment by thinkyhead** [comment]
Great! Sometimes I wish we could just import content from that wiki, but linking to those pages from the relevant topics will be a good enhancement.
