### ISSUE TITLE
Missing "S" parameter in documentation for G0/G1/G2/G3/G5 commands

### ISSUE THREAD

**Issue by mak0t0san** [MarlinFirmware/MarlinDocumentation#398]
Would be nice to have a note mentioning the S parameter that can be used with movement commands if `LASER_MOVE_POWER` is defined in Configuration_adv.h

The comment in the code currently reads:
> Include laser power in G0/G1/G2/G3/G5 commands with the 'S' parameter

**Comment by shitcreek** [comment]
it's already there, but I went a head and added an additional note. thanks.
