### ISSUE TITLE
How to just see doc (link?)

### ISSUE THREAD

**Issue by altimmons** [MarlinFirmware/MarlinDocumentation#416]
Add explanation in README.md that explains how to just see the doc.  Its a great explanation of how to contribute, but right now i just want to see it.

**Comment by thisiskeithb** [comment]
This repo is the code behind https://marlinfw.org/, so you'll want to visit that website to view documents / pages / examples.

**Comment by thinkyhead** [comment]
Thanks for the suggestion! I've added a link to the published documentation website to the README.
