### ISSUE TITLE
Jekyll 3 upgrade - Rouge vs.  Pygments.rb  & other changes

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [MarlinFirmware/MarlinDocumentation#42]
While playing with the 20 Oct merge I got a message to upgrade to Jekyll 3 (which I did).  The [Jekyll upgrade page](http://jekyllrb.com/docs/upgrading/2-to-3/) talks about using Rouge instead of Pygments.rb as the highlighter.

Should we start using Rouge?

There were a lot of other changes listed in the upgrade link.  Are there any that we need to be paying attention to?

**Comment by landodragon141** [comment]
I just glanced through and didn't see anything that look super important. From what I see on Rouge I don't see any reason not to use it.

**Comment by jbrazio** [comment]
In fact we already use Rouge as the highlighter.
