### ISSUE TITLE
Bed temperature setup issue

### ISSUE THREAD

**Issue by belial1** [MarlinFirmware/MarlinDocumentation#434]
Have problem with timing for bed temperature . 
CR10V3 printer, Marlin 2.0.9.3.
Ambient temp. around 14 deg С. 
ABS+ plastic need abt 15 min to heat up bed to 115. 
So after 10 min bed warming always receive error " bed temp, reset printer" message. 
And printer freeze.
Is it possible to adjust timeout for bed temp. settings independant of plastic type and add it for settings?

**Comment by thisiskeithb** [comment]
> Ambient temp. around 14 deg С.
> ABS+ plastic need abt 15 min to heat up bed to 115.

Put your printer in an enclosure. You will continue to have issues trying to heat a bed that size, to those temperatures, in a room that cold.

---

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
