### ISSUE TITLE
Typo in Configuratio_adv.H

### ISSUE THREAD

**Issue by inspectionsbybob** [MarlinFirmware/MarlinDocumentation#449]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

MINOR Typo in the Marlin documentation

In Configuration_Adv.H

Mode 0: Full Control Mode. ([M605](https://marlinfw.org/docs/gcode/M605.html) **S1**) Slicers that fully support dual X-carriages can use this mode for optimal travel results.
Mode 1: Auto-park Mode. (M605 **S1**) The firmware automatically parks/unparks the carriages on tool-change. No slicer support is required. ([M605](https://marlinfw.org/docs/gcode/M605.html) S1)

It calls out S1 for BOTH Full Control and AutoPark and other modes as well.
Looks like a Cut-n-paste error.

The Documentation for M605 is correct.

### Bug Timeline

Allways

### Expected behavior

Typo

### Actual behavior

should be S0 and S1

### Steps to Reproduce

Open documentation

### Version of Marlin Firmware

current online documentation 

### Printer model

NA

### Electronics

NA

### Add-ons

NA

### Additional information & file uploads

![Screenshot (32)](https://user-images.githubusercontent.com/22258531/165770978-67ce30a5-5dc0-44cd-a765-365d02d138ae.png)

**Comment by thinkyhead** [comment]
Documentation updated, thanks!
