### ISSUE TITLE
Documentation Suggestion - Identify versions for options

### ISSUE THREAD

**Issue by dstrohl** [MarlinFirmware/MarlinDocumentation#461]
It would be helpful to identify which version(s) support which configuration options.   Or, as an alternative, have different configuration pages for different versions.

I'm using v2.1, and found some options no longer existed (the number of z motors) and instead it counts the configured drivers (which totally makes sense, but the docs are not up to date)... and if I was using an older version, it would be good to know what options are no supported on that platform.

As a really cool additional function, it would be really cool to be able to filter the options by board, allowing boards to be defined which will hide/show the options not supported by those boards.  (I suspect this is harder than it sounds, but I figured I'd throw it out there.)

**Comment by thinkyhead** [comment]
Thanks for the suggestion! The work to automate this kind of documentation is underway.
