### ISSUE TITLE
EX.xxx Calucaltion in Marlin Code

### ISSUE THREAD

**Issue by fbuna** [MarlinFirmware/MarlinDocumentation#473]
Hello,
I want to know how do I get the individual E positions out when approaching the individual points in the X, Y and Z direction (GCode Marlin)? So how does the GCode get all the exact EXxx values? Where can I find this calculation for the different EPositions (how much filament in each new x-,y- , positions will be needed) in Marlin Code?

thx :)

**Comment by ellensp** [comment]
This Issue Queue is for Marlin Documentation and related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with questions, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y
