### ISSUE TITLE
Unified bed leveling click

### ISSUE THREAD

**Issue by BillStruve** [MarlinFirmware/MarlinDocumentation#48]
Leads to a Document Unknown page.

**Comment by thinkyhead** [comment]
Yes. Still awaiting help from the owner of the domain @jbrazio to allow us to update the site.

**Comment by jbrazio** [comment]
@thinkyhead I was supposed to help out begging of this week but only today I was able to do it.
I saw you're able to work it out by yourself in the meanwhile. Nevertheless I've updated the README with the script I use for easy publishing.

**Comment by thinkyhead** [comment]
Yep, I finally took the time to read through it all, and also updated the README with the info I was able to gather about getting set up on macOS.
