### ISSUE TITLE
M593 schouldnt start with 0Hz

### ISSUE THREAD

**Issue by TylonHH** [MarlinFirmware/MarlinDocumentation#499]
Regarding to: https://github.com/MarlinFirmware/MarlinDocumentation/edit/master/_gcode/M593.md

I used the code for Prusa:
`M593 F{(layer_num < 2 ? 0 : 15 + 45.0 * (layer_num - 2) / 297)} ; Hz Input Shaping Test`
As I see the Freq is set to 0Hz at the layer <2.
But there will be no movement with this Frequenz! Will it?

So the code should look like:
`M593 F{(layer_num < 2 ? 15 : 15 + 45.0 * (layer_num - 2) / 297)} ; Hz Input Shaping Test`

Tell me if I'm wrong

**Comment by thisiskeithb** [comment]
That just zeroes out the damping frequency. It doesn't stop motion.
