### ISSUE TITLE
Auto Build Not Allowing Me To Set Correct Board

### ISSUE THREAD

**Issue by Jaxer6563** [MarlinFirmware/MarlinDocumentation#505]
I'm trying to compile Marlin 2.1.x firmware for My Ender 3 Pro, and I have Auto Build and PlatformIO in VSCode.
I have gone in an made sure the board is set to BOARD_CREALITY_V4, however, after refreshing the Auto Build Tab, It still has the board set to RAMPS 1.4. I'm unsure of why it is doing so. I can't use the Configuration tab like it says to [here](https://marlinfw.org/docs/basics/auto_build_marlin.html) because the tab says its under contruction.

If I try to access PlatformIO's home tab, It just gets stuck with a black tab with loading and nothing happens.

**Comment by ellensp** [comment]
This is the Marlin Documentation github, for editing and adding to the Marlin documentation pages. Not a support forum

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).
