### ISSUE TITLE
M206 description page

### ISSUE THREAD

**Issue by tocguy** [MarlinFirmware/MarlinDocumentation#521]
Minor page error. The Related Codes tidbit at the top of the page lists codes M428 and M92. M428 is ok but M92 has to do with esteps rather than Home Offsets. I think the M92 should be G92.

M206: https://marlinfw.org/docs/gcode/M206.html

**Comment by thinkyhead** [comment]
Oops, I meant `G92` not `M92`. Always mixing those up.
