### ISSUE TITLE
New feature: IS calibration tool

### ISSUE THREAD

**Issue by KimmoHop** [MarlinFirmware/MarlinDocumentation#527]
@tombrazier has created FR https://github.com/MarlinFirmware/Marlin/issues/26166 to include simple IS calibration patterns in M593 command. He also gives python script to create calibration patterns. ( It is rather fast and funny, though also a little scary, to watch and hear the printer - with all the shaky parts shakin' - print the patterns :D )

I thought I'd give a try at converting python script to JS tool, like linear advance calibration pattern tool, in Marlin documentation. First idea was to create Cura plugin (python included) but this way seemed easier to use. Page started as shameless copy of linear advance tool page and settings look pretty much the same.

Current state can be seen in PR https://github.com/MarlinFirmware/MarlinDocumentation/pull/524. Though no longer draft, it does lack proper images to help users interpret their results. I'll try to create better pattern prints with thicker layer. Modifying my printer a bit (Creality heatsink -> V6 heatsink, either keeping Volcano or going to V6 + clone CHT) might or might not improve stability.

All feedback, including Guidance to words with Capital letters (I don't think it's fully consistent on LA page either) is welcome!

**Comment by tombrazier** [comment]
Great work @KimmoHop. Thank you so much for doing it.
