### ISSUE TITLE
Consolidation of code for 1284p

### ISSUE THREAD

**Issue by Psyc0Flyer** [MarlinFirmware/MarlinDocumentation#63]
I was wondering what all I can remove from code if I have very specific hardware? I am using a Melzi (Sanguino) board `#63` with SD support, Heated bed, 1X, 1Y, 1Z, 1E, BLTouch and a RepRap Discount Full Graphics Display? I want to have all of the functions of the most current Marlin but a Jenny Craig version. Any and all help would be greatly appreciated!

TIA!

**Comment by thinkyhead** [comment]
There is no need to strip out code. Marlin only compiles in the code it needs for the features you have enabled. To get a smaller build, turn off the features you don't need.

**Comment by Psyc0Flyer** [comment]
That is what I am asking. I have only selected what I need (I think) and it tells me it is over by 6002 bytes :/

**Comment by fiveangle** [comment]
setting NO_WORKSPACE_OFFSETS in advance config is usually an easy way to get a few k back

`#define NO_WORKSPACE_OFFSETS`

**Comment by thinkyhead** [comment]
See if the new `bugfix-1.1.x` is slimmer. We've done a bunch of optimization to try and reduce SRAM usage. 6002 bytes over sounds very strange. Even with a full configuration, Marlin should only use around 5K of SRAM.

**Comment by fiveangle** [comment]
It's a 128k board so I'm sure he's talking about PROGMEM. Surprised it's only 6k over with all that stuff enabled. Disabling workspace offsets, cold extrusion prevention, disable 503, and maybe a few other small things should get you there.
