### ISSUE TITLE
Got a compiler error: can't assign float num to parameters

### ISSUE THREAD

**Issue by GregHC** [MarlinFirmware/MarlinDocumentation#73]
I was setting up the auto bed leveling parameters when I encountered the "floating constant in preprocessor expression" error.

#define X_PROBE_OFFSET_FROM_EXTRUDER 1.23
#define Y_PROBE_OFFSET_FROM_EXTRUDER -8.3 
#define Z_PROBE_OFFSET_FROM_EXTRUDER -14.3

Arduino reports this error if I use floating numbers. Meanwhile fixed parameters will certainly pass compilation.

Trying to fix it. Anyone got some tips?

**Comment by thinkyhead** [comment]
True. The X and Y offsets must be whole numbers, no decimal points.
