### ISSUE TITLE
M203 units in docs are incorrect

### ISSUE THREAD

**Issue by chrissv** [MarlinFirmware/MarlinDocumentation#96]
In the M203 document: http://marlinfw.org/docs/gcode/M203.html
the units for the example are incorrect. The doc says:

> Set max feedrate for XY to 100mm/s:
> M203 X6000 Y6000

But the example "X6000" and "Y6000" look to be in units of mm/min.
Should they be instead?:
> M203 X100 Y100

**Comment by dborden0** [comment]
This example confused me. I think chrissv is correct.

**Comment by thinkyhead** [comment]
Corrected, thanks!

**Comment by chrissv** [comment]
Still incorrect. The docs have "Y1000" instead of "Y100"...
