### ISSUE TITLE
Motor Steps Chart

### ISSUE THREAD

**Issue by sarf2k4** [MarlinFirmware/MarlinDocumentation#98]
Hi, 

I wanted to add my own content but I'm unable to get jekyll and bundle/bundler installed with ruby. I got some errors. Therefore I don't know how to troubleshoot this thing (although someone did helped me last time) but that was I think last year.

I need help in getting the motor steps chart all into one place.

**Comment by shitcreek** [comment]
Did you ever get this sorted out?
